version: 2.1

commands:
  ros_build:
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source /opt/ros/*/setup.bash
            mkdir -p ~/catkin_ws/src
            ln -s "$PWD" ~/catkin_ws/src/
            cd ~/catkin_ws
            rosdep update && rosdep install --from-paths src/ --ignore-src -y
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            source /opt/ros/*/setup.bash
            cd ~/catkin_ws
            catkin build -j 2 --no-status
      - run:
          name: Run Tests
          command: |
            source /opt/ros/*/setup.bash
            cd ~/catkin_ws
            catkin run_tests avt_vimba_camera --no-deps
            catkin_test_results
jobs:
  noetic:
    docker:
      - image: autonomoustuff/docker-builds:noetic-ros-base
    steps:
      - ros_build
    working_directory: ~/src

workflows:
  ros_build:
    jobs:
      - noetic
